const slidesWrapper = document.querySelector('.meme__wrapper'),
      slidesField = document.querySelector('.meme__inner'),
      width = window.getComputedStyle(slidesWrapper).width,
      slides = document.querySelectorAll('.meme__slide'),
      sliderDot = document.querySelectorAll('.meme__dot-wrapper'),
      dots = document.querySelectorAll('.meme__dot'),
      phrase = document.querySelector('.meme__phrase'),
      slide = slides[0];
let widthSlide = window.getComputedStyle(slide).width,
      slideIndex = 1,
      offset = 0;